### ISSUE TITLE
Error invoking SKY_cipher_GenerateDeterministicKeyPairs

### ISSUE THREAD

**Issue by olemis** [skycoin/pyskycoin#73]
This is what seems to be wrong .

```python
>>> import skycoin as s
>>> seed = 'x'
>>> seckeys = s.cipher_SecKeys()
>>> err = s.SKY_cipher_GenerateDeterministicKeyPairs(s, 4, seckeys)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NotImplementedError: Wrong number or type of arguments for overloaded function 'SKY_cipher_GenerateDeterministicKeyPairs'.
  Possible C/C++ prototypes are:
    wrap_SKY_cipher_GenerateDeterministicKeyPairs(GoSlice,GoInt,cipher_SecKeys *)
    SKY_cipher_GenerateDeterministicKeyPairs(GoSlice,GoInt,coin__UxArray *)
>>> err = s.SKY_cipher_GenerateDeterministicKeyPairs(bytes(ord('x')), 4, seckeys)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NotImplementedError: Wrong number or type of arguments for overloaded function 'SKY_cipher_GenerateDeterministicKeyPairs'.
  Possible C/C++ prototypes are:
    wrap_SKY_cipher_GenerateDeterministicKeyPairs(GoSlice,GoInt,cipher_SecKeys *)
    SKY_cipher_GenerateDeterministicKeyPairs(GoSlice,GoInt,coin__UxArray *)
```

**Comment by stdevHan** [comment]
@olemis The problem is that you are sending as parameter the alias of the skycoin module

`
>>> import skycoin as s
>>> seed = 'x'
>>> seckeys = s.cipher_SecKeys()
>>> err = s.SKY_cipher_GenerateDeterministicKeyPairs(s, 4, seckeys)`

`s` is module `skycoin` , not `GoSlice`
